project_id = "fcdzhsqssfqqjlirvlkg"

[functions.game-create]
verify_jwt = true

[functions.game-join]
verify_jwt = true

[functions.game-action]
verify_jwt = true

[functions.game-state]
verify_jwt = true
